### ISSUE TITLE
Wrap and noWrap required.

### ISSUE THREAD

**Issue by shtse8** [donatj/CLI-Toolkit#4]
Don't wrap for the following text:
\033[?7l

Wrap for the following txt:
\033[?7h

**Comment by donatj** [comment]
Interesting, I will look into adding these.

**Comment by shtse8** [comment]
Any updates?

**Comment by donatj** [comment]
I need to make some decisions on how I want to implement them, and I've been super sick the last couple weeks. On top of that I'm going to Las Vegas on tuesday, lol. If I find the time tomorrow I'll review - it's not forgotten, just a lot going on at the moment ;)

**Comment by shtse8** [comment]
Any updates?

**Comment by donatj** [comment]
I'm so sorry I forgot about this! Holy cow. I'm legitimately putting an event on my calendar for midday tomorrow to look at this! Thank you for your continued patience, and my sincere appoligies!

**Comment by shtse8** [comment]
Thanks.

**Comment by donatj** [comment]
Cursor now has a method "wrap" that takes a bool, e.g. disable wrap via `Cursor::wrap(false);`

**Comment by donatj** [comment]
It has been tagged in release v0.2.0
